version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: backend
    restart: always
    env_file: ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 4
    depends_on:
      - db

  db:
    image: postgres:14.2
    container_name: db
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    restart: always

volumes:
  postgres_data:
